### ISSUE TITLE
Process: Explore accurately capturing visual information for spec flow chart via automated process.

### ISSUE THREAD

**Issue by grace-spitzer-wong** [GSS-Cogs/family-homelessness#41]
Need a way to marry up csv downloads as there will be a discrepancy between the data collected via scraper. Key aim is to visualise how tabs etc in a spreadsheet have been combined or separated out into cubes.

**Comment by MartynBSpooner** [comment]
Take this up with John and Mike - gather specs. Refine use cases.

**Comment by grace-spitzer-wong** [comment]
Leigh has produced one via D3.js - will look into that and see if it replicates the original and captures the info we need. Will also get in touch with John and Mike.

**Comment by grace-spitzer-wong** [comment]
Completed - information captured in new covid charts
